### ISSUE TITLE
SS for iOS缺少一个黑名单机制

### ISSUE THREAD

**Issue by akar1nchan** [linusyang/MobileShadowSocks#51]
https://github.com/akar1nchan/gfvvlist/blob/master/proxy.pac

目前只有白名单和全局  而白名单是除了国内ip其他都是走代理 比较耗费代理服务器的流量
如果走黑名单就可以节省代理服务器的流量  判断可以在本地pac解决

**Comment by shellexy** [comment]
界面里可以不要用默认 pac 而是填自己的黑名单 pac 呀

**Comment by akar1nchan** [comment]
不是每个用户都会自己换 pac
