### ISSUE TITLE
可以看错误日志吗

### ISSUE THREAD

**Issue by ElfSundae** [linusyang/MobileShadowSocks#52]
我手机是6 Plus, 8.1.2, 有时能用有时用不了, 下载了app内代理也不行, 我还原了下网络设置再设置又好了, 我添加了好几个配置, 用的自己的pac, 连不上时我就折腾这折腾那.. 也没定位出是配置的问题还是插件的bug.. 有没有地方可以看错误日志?

**Comment by ElfSundae** [comment]
好像是我自己的pac端口不对..我用的是1080, 请问哪里可以改socket端口? @linusyang

**Comment by zsm1703** [comment]
通过默认pac改吧。全局肯定没问题的。

**Comment by ElfSundae** [comment]
@zsm1703 哦, 谢谢
