### ISSUE TITLE
添加FlipControlCenter快捷开关插件

### ISSUE THREAD

**Issue by eric1932** [linusyang/MobileShadowSocks#55]

**Comment by linusyang** [comment]
Consider contributing one? :)

**Comment by eric1932** [comment]
能力有限，不知道可不可以

linusyang <notifications@github.com>于2015年2月17日星期二写道：

> Consider contributing one? :)
>
>
>
> > On Feb 17, 2015, at 10:43 PM, eric1932 <notifications@github.com

**Comment by linusyang** [comment]
Personally I don't like FlipControl or Activator. They are too heavy and need more time to be compatible with new iOS versions. So I won't use such switch or shortcut even if I would write one. :P

**Comment by eric1932** [comment]
好吧谢谢了（话说你英语不错）

linusyang <notifications@github.com>于2015年2月17日星期二写道：

> Personally I don't like FlipControl or Activator. They are too heavy and
> need more time to be compatible with new iOS versions. So I won't use such
> switch or shortcut even if I would write one. :P
>
>
>
> > On Feb 17, 2015, at 10:47 PM, eric1932 <notifications@github.com

**Comment by linusyang** [comment]
Thanks :D
